name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-${{ runner.OS }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.OS }}-${{ env.cache-name }}
            yarn-${{ runner.OS }}-
      - name: Install dependencies
        # "--frozen-lockfile" doesn't work, see https://github.com/yarnpkg/yarn/issues/5840
        run: |
          yarn install
          if [[ -n "$(git status -s yarn.lock)" ]] ; then
            echo "yarn.lock is outdated"
            exit 1
          fi
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
